services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: timm2
      POSTGRES_PASSWORD: dontforget3oct11escapethematrixniclasstaysolidrocky5801
      POSTGRES_DB: ai_bot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5431"

  bot:
    build: .
    depends_on:
      - db
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      COMMAND_PREFIX: ${COMMAND_PREFIX}
      DATABASE_URL: postgresql+asyncpg://timm2:dontforget3oct11escapethematrixniclasstaysolidrocky5801@db:5431/ai_bot_db
    volumes:
      - .:/app
    command: python main.py

volumes:
  pgdata:
