services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER:-timm2}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dontforget3oct11escapethematrixniclasstaysolidrocky5801}
      POSTGRES_DB: ${POSTGRES_DB:-ai_bot_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5431"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-timm2} -d ${POSTGRES_DB:-ai_bot_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      COMMAND_PREFIX: ${COMMAND_PREFIX:-!}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-timm2}:${POSTGRES_PASSWORD:-dontforget3oct11escapethematrixniclasstaysolidrocky5801}@db:5432/${POSTGRES_DB:-ai_bot_db}
    volumes:
      - .:/app
    command: python main.py
    restart: unless-stopped

volumes:
  pgdata:
